# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-26 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesyeux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='user_dps')),
                ('idnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(null=True, upload_to='neighborhood_photos'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='ambulance',
            field=models.CharField(blank=True, default='911', max_length=12),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='location',
            field=models.CharField(blank=True, default='Somewhere in Nairobi', max_length=100),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='police',
            field=models.CharField(blank=True, default='911', max_length=12),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='population',
            field=models.CharField(blank=True, default='Unknown', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Neighborhood',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lesyeux.Neighborhood'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
