# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-26 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesyeux', '0003_neighborhood_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='slug',
        ),
    ]
