# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-26 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesyeux', '0004_remove_neighborhood_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_details',
        ),
    ]
