# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-26 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesyeux', '0008_auto_20180526_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
