# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-27 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesyeux', '0010_auto_20180526_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesyeux.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images'),
        ),
    ]
