# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-27 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lesyeux', '0011_auto_20180527_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Neighborhood',
            new_name='neighborhood',
        ),
        migrations.AddField(
            model_name='business',
            name='neighborhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lesyeux.Neighborhood'),
            preserve_default=False,
        ),
    ]
