# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-05-27 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesyeux', '0012_auto_20180527_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='additional_details',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
